apiVersion: backstage.io/v1alpha1
kind: Domain
metadata:
  name: artists
  description: Everything about artists
spec:
  owner: guests
---
apiVersion: backstage.io/v1alpha1
kind: Domain
metadata:
  name: btists
  description: Everything about artists
spec:
  owner: guests
